### ISSUE TITLE
Registration part looks a bit of mess, can we put somehow in order where each information is easy to find https://2023.foss4g.org/register/

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#62]

**Comment by jbelien** [comment]
@valmirmustafa Sure ... I just copy pasted the content from the Word document.

Let me know how you want to structure it.

**Comment by valmirmustafa** [comment]
Just to make it more readable. 

- Here instead of price table we will design one and put it there. 

- Divide titles from the text below - You can see that paragraph of Business to Business, it is almost sticked with Social programme title. 

- the same should follow with Travel Grant

- VISA Info 
leave only this text: 
_Kosovo requires visas for citizens of certain countries. You can find more information on which participants will need a visa to come to Kosovo here: https://en.wikipedia.org/wiki/Visa_policy_of_Kosovo

FLOSSK will issue a visa invitation letter should you need one and will facilitate the visa process so you don’t need to visit a Kosovo Consulate._ 
the rest can go as a special page with a button VISA INFO here

- Visa INFO button can be added at Attending page where visa info is
